.catalog:
  name: NRT Stack
  version: NRT-1.0.0
  description: |
    NRT Stack With All Components.
  minimum_rancher_version: v0.56.0
  maintainer: "Pawan Kumar <monu.pawan@gmail.com>"
  questions:
    - variable: "zk_scale"
      description: "Number of zk nodes. Note: Recommended an odd number"
      label: "Zk Nodes:"
      required: true
      default: 5
      type: "int"
    - variable: "zk_mem"
      description: "Amount of memory to config zk."
      label: "Zk Memory (mb):"
      required: true
      default: 2048 
      type: "string"
    - variable: "hz_scale"
      description: "Number of Hazelcast loader nodes(excluding mancenter node)"
      label: "Hz Loader Nodes(excluding mancenter):"
      required: true
      default: 1
      type: "int"
    - variable: "hz_init_frac"
      description: "CMS Initiating Occupancy Fraction"
      label: "CMS Initiating Occupancy Fraction:"
      required: true
      default: 60
      type: "int"
    - variable: "hz_max_heap_free"
      description: "Max Heap Free Ratio for Hazelcast loader"
      label: "Max Heap Free Ratio :"
      required: true
      default: 50 
      type: "int"
    - variable: "hz_min_heap_free"
      description: "Min Heap Free Ratio for Hazelcast loader"
      label: "Min Heap Free Ratio:"
      required: true
      default: 20 
      type: "int"
    - variable: "hz_heap_size"
      description: "Maximum heap size for Hazelcast loader"
      label: "Hz Heap (GB):"
      required: true
      default: 25 
      type: "string"
    - variable: "Cassandra_link"
      description: |
        Choose the Cassandra string to use. 
      label: "Casandra stack/string"
      default: "Cassandra/cass"
      required: true
      type: "string"
    - variable: "kafka_scale"
      description: "Number of Kafka brokers nodes. Note: Recommended an odd number"
      label: "Broker Nodes:"
      required: true
      default: 3
      type: "int"
    - variable: "kafka_mem"
      description: "Amount of memory to config Kafka brokers."
      label: "Broker Memory (mb):"
      required: true
      default: 1024 
      type: "string"
    - variable: "kafka_log_dir"
      description: "Kafka Broker volume to log data"
      label: "Broker log volume:"
      required: true
      default: "/usr/local/kafka/logs"
      type: "string"
    - variable: "kafka_log_retention"
      description: "Kafka Broker log retention in hours"
      label: "Broker log retention (h):"
      required: true
      default: "168"
      type: "int"
    - variable: "kafka_num_partitions"
      description: "Number of Kafka broker partitions"
      label: "Broker partitions:"
      required: true
      default: "1"
      type: "int"
    - variable: "kafka_interval"
      description: "Interval to poll/apply configuration changes. 0 to disable" 
      label: "Broker Interval (s):"
      required: true
      default: 60 
      type: "int"
    - variable: "kafka_pub_ip"
      description: "Advertise Kafka host ip in zookeeper" 
      label: "Advertise host ip:"
      required: false
      default: false 
      type: "boolean"
    - variable: "ncm_scale"
      description: "Number of Nifi Cluster Manager nodes"
      label: "ncm Nodes:"
      required: true
      default: 1
      type: "int"
    - variable: "worker_scale"
      description: "Number of Nifi worker nodes"
      label: "worker Nodes:"
      required: true
      default: 1
      type: "int"
    - variable: "zk_link"
      description: |
        Choose the Zookeeper string to use. 
        It's really recommended a dedicated zookeeper string just for Nifi.
      label: "Zookeeper stack/string"
      default: "zk/zk"
      required: true
      type: "string"
    - variable: "nimbus_scale"
      description: "Number of Nimbus nodes"
      label: "nimbus Nodes:"
      required: true
      default: 1
      type: "int"
    - variable: "supervisor_scale"
      description: "Number of supervisor nodes"
      label: "supervisor Nodes:"
      required: true
      default: 3
      type: "int"
    - variable: "ui_scale"
      description: "Number of ui nodes"
      label: "ui Nodes:"
      required: true
      default: 1
      type: "int"
    - variable: "HazelcastETL_link"
      description: |
        Choose the Hazelcast string to use. 
      label: "HazelcastETL stack/string"
      default: "HazelETL/ETL"
      required: true
      type: "string"
    - variable: "HazelcastNONETL_link"
      description: |
        Choose the Hazelcast string to use. 
      label: "HazelcastNONETL stack/string"
      default: "HazelcastNONETL/NONETL"
      required: true
      type: "string"
    - variable: "Kafka_link"
      description: |
        Choose the Kafka string to use. 
      label: "Kafka stack/string"
      default: "Kafka/broker"
      required: true
      type: "string"
    - variable: "RabbitMq_link"
      description: |
        Choose the RabbitMq string to use. 
      label: "RabbitMq stack/string"
      default: "Rabbitmq/rabbit"
      required: true
      type: "string"
    - variable: "Nifi_link"
      description: |
        Choose the Apache Nifi string to use. 
      label: "Nifi stack/string"
      default: "Nifi/worker"
      required: true
      type: "string"
zk:
 scale: ${zk_scale}
Cassandra-Seed:
  scale: ${seed_scale}
  retain_ip: true
Cassandra-Peer:
  scale: ${cassandra_scale}
  retain_ip: true     
Kafka-broker:
  scale: ${kafka_scale}
  retain_ip: true
  health_check:
    port: 9092
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000   
Nifi-ncm:
 scale: ${ncm_scale}
Nifi-worker:
 scale: ${worker_scale}   
Storm-nimbus:
 scale: ${nimbus_scale}
Storm-supervisor:
 scale: ${supervisor_scale}
Storm-ui:
 scale: ${ui_scale}
